Enumerable.Range(0, Int32.MaxValue)
    .Select(static v => v % 15 == 0 ? "FizzBuzz" : v % 3 == 0 ? "Fizz" : v % 5 == 0 ? "Buzz" : v.ToString())
    .Select(static o => (Output: o, Amplitude: 80, Period: 0.05d))
    .Select(static (t, i) => (t.Amplitude, t.Output, Sine: Console.WindowWidth / 2 + (Int32)(Math.Sin(t.Period * i) * t.Amplitude)))
    .Select(static (t, i) => (t.Output, t.Sine, Color: (ConsoleColor)(i / 3 % 15 + 1)))
    .Select(static t => { Console.ForegroundColor = t.Color; return t; })
    .Select(static t => { Console.CursorLeft = t.Sine; return t; })
    .Select(static t => (Delay: 1, t.Output))
    .Select(static t => { Thread.Sleep(t.Delay); return t.Output; })
    .Select(static o => { Console.WriteLine(o); return 0; })
    .ToArray();